[build]
  publish = "."
  command = "echo 'Building...'"

[functions]
  directory = "plataforma-ird/netlify/functions"

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
